"""Generate an AI News PDF report using fpdf2 (Unicode via Arial TTF)."""
from fpdf import FPDF

ACCENT = (23, 74, 133)      # dark blue
LIGHT = (235, 241, 250)     # light blue bg
GREY = (90, 90, 90)
DARK = (40, 40, 40)
FONT_DIR = "C:/Windows/Fonts"

SECTIONS = [
    {
        "title": "OpenAI: GPT-5.6, ChatGPT Work & GPT-Live",
        "items": [
            ("GPT-5.6 (Sol, Terra, Luna) broadly released July 9, 2026",
             "Rollout was staggered per a U.S. government request. Terra API pricing: $2/M input, $12/M output; Luna: $0.20/M input, $1.20/M output (from July 30). Free accounts remain on GPT-5.5."),
            ("ChatGPT Work and Codex tools",
             "OpenAI positions ChatGPT as \"a partner for your most ambitious work\", adding usage analytics and deeper agentic capabilities."),
            ("GPT-Live introduced (July 9, 2026)",
             "A next-generation interactive product previewed alongside GPT-5.6; Voice expands to Work and Codex in the desktop app."),
            ("Health in ChatGPT (July 23, 2026)",
             "New health-oriented capabilities; separate effort on ChatGPT for Academic Researchers (July 29) to accelerate scientific discovery."),
        ],
    },
    {
        "title": "China's Open-Weight Models Close the Gap",
        "items": [
            ("Z.ai climbs above Anthropic on OpenRouter",
             "Reuters analysis (July 2, 2026): an inexpensive Chinese open-weight model now ranks above Anthropic's models on third-party developer platforms."),
            ("Industry praise",
             "David Sacks: \"We now have a Chinese open-weight model that is as good as the currently available models from OpenAI and Anthropic.\" Snowflake CEO Sridhar Ramaswamy and Marc Andreessen also lauded it."),
            ("NYT coverage",
             "Z.ai is at the cutting edge of a wave of powerful, inexpensive Chinese models challenging OpenAI, Anthropic and Google's lock on the industry."),
        ],
    },
    {
        "title": "Security: Critical MCP Vulnerability (CVSS 10.0)",
        "items": [
            ("Ruflo 'RufRoot' flaw - CVE-2026-59726",
             "Noma Labs disclosed a maximum-severity flaw in the open-source AI agent platform Ruflo (67K+ GitHub stars, #2 on MCPMarket). A single unauthenticated HTTP POST to the MCP bridge on port 3001 could execute code and exfiltrate LLM API keys, exposing ~233 tools."),
        ],
    },
    {
        "title": "AI in Science & the Data Problem",
        "items": [
            ("Hallucinations as a research tool",
             "AI's so-called \"hallucinations\" are proving transformative in scientific research, helping generate novel hypotheses."),
            ("Pollution of training data",
             "Analysts warn the cheap, permissionless text that powered the first LLM boom is becoming polluted by AI output, contested by owners, and costly to replace - a growing constraint for frontier labs."),
        ],
    },
    {
        "title": "Robotics & Funding",
        "items": [
            ("Warehouse robotics boom",
             "Mytra raised $78M across three rounds for warehouse automation; Munich-based RobCo raised $42.5M in February for flexible robotic hardware kits."),
        ],
    },
]

class Report(FPDF):
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("Arial", "I", 9)
        self.set_text_color(*GREY)
        self.cell(0, 8, "AI News Report  |  August 2, 2026", align="R")
        self.ln(6)
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.4)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-14)
        self.set_font("Arial", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 8, f"Generated by TOMAS Agent  |  Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        self.set_font("Arial", "B", 13)
        self.set_text_color(*ACCENT)
        self.set_fill_color(*LIGHT)
        self.cell(0, 10, title, fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def news_item(self, head, body):
        self.set_font("Arial", "B", 10.5)
        self.set_text_color(*DARK)
        self.multi_cell(0, 5.5, "\u2022 " + head, new_x="LMARGIN", new_y="NEXT")
        self.set_font("Arial", "", 9.5)
        self.set_text_color(*GREY)
        self.set_x(self.l_margin + 5)
        self.multi_cell(0, 5, body, new_x="LMARGIN", new_y="NEXT")
        self.ln(2.5)

def build():
    pdf = Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(18, 18, 18)
    for style, fname in [("", "arial.ttf"), ("B", "arialbd.ttf"),
                         ("I", "ariali.ttf"), ("BI", "arialbi.ttf")]:
        pdf.add_font("Arial", style, f"{FONT_DIR}/{fname}")
    pdf.add_page()

    # Cover header
    pdf.set_fill_color(*ACCENT)
    pdf.rect(0, 0, pdf.w, 62, "F")
    pdf.set_y(20)
    pdf.set_font("Arial", "B", 26)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 12, "AI NEWS REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Arial", "", 13)
    pdf.cell(0, 8, "Latest developments in artificial intelligence", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Arial", "I", 10.5)
    pdf.cell(0, 8, "Compiled: August 2, 2026  |  Generated by TOMAS Agent", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(80)
    pdf.set_text_color(*DARK)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 9, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)
    pdf.set_font("Arial", "", 10.5)
    pdf.multi_cell(0, 6,
        "This report summarizes the most significant AI developments of the past week: OpenAI's broad release of "
        "GPT-5.6 along with ChatGPT Work and GPT-Live; a Chinese open-weight model (Z.ai) climbing above Western "
        "frontier models on usage charts; a maximum-severity (CVSS 10.0) vulnerability in the Ruflo MCP agent "
        "platform; and new momentum for AI in scientific discovery. Sources include Reuters, Axios, TechCrunch, "
        "OpenAI Newsroom, AI Weekly and The New York Times.",
        new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    for sec in SECTIONS:
        pdf.section_title(sec["title"])
        for head, body in sec["items"]:
            pdf.news_item(head, body)

    # Sources
    pdf.section_title("Sources")
    sources = [
        "OpenAI Newsroom - openai.com/news",
        "Reuters - reuters.com/technology/artificial-intelligence",
        "Axios - axios.com/2026/07/09/ai-openai-gpt-release",
        "The New York Times - nytimes.com (Z.ai coverage, June 25, 2026)",
        "AI Weekly - aiweekly.co/ai-news-today",
        "Noma Labs / CVE-2026-59726 disclosure",
        "TechCrunch AI - techcrunch.com/category/artificial-intelligence",
    ]
    for s in sources:
        pdf.set_font("Arial", "", 9.5)
        pdf.set_text_color(*GREY)
        pdf.set_x(pdf.l_margin + 5)
        pdf.multi_cell(0, 5.5, "\u2013 " + s, new_x="LMARGIN", new_y="NEXT")

    out = "AI_News_Report_2026-08-02.pdf"
    pdf.output(out)
    print("Wrote", out)

if __name__ == "__main__":
    build()
