"""
Self-Notes — the agent writes notes about itself: lessons learned,
patterns noticed, decisions made, and insights gained.

Notes are stored under ~/.tomas/self-notes/ as individual markdown files
with YAML frontmatter for metadata.
"""

from __future__ import annotations

import json
import os
import re
import time
import hashlib
from pathlib import Path
from typing import Any, Optional

# ── Constants ──────────────────────────────────────────────────

TOMAS_DIR = Path.home() / ".tomas"
NOTES_DIR = TOMAS_DIR / "self-notes"
NOTES_INDEX = NOTES_DIR / "index.json"

MAX_NOTES = 200

NOTE_TYPES = {"lesson", "pattern", "decision", "insight", "tip", "warning"}


# ═══════════════════════════════════════════════════════════════
#  Path helpers
# ═══════════════════════════════════════════════════════════════

def _ensure_dirs() -> None:
    """Create the self-notes directory if it doesn't exist."""
    NOTES_DIR.mkdir(parents=True, exist_ok=True)


def _note_path(note_id: str) -> Path:
    """Return the full path to a note file."""
    return NOTES_DIR / f"{note_id}.md"


# ═══════════════════════════════════════════════════════════════
#  ID generation
# ═══════════════════════════════════════════════════════════════

def _generate_note_id() -> str:
    """Generate a unique note ID."""
    ts = time.strftime("%Y%m%d_%H%M%S", time.localtime())
    rand = hashlib.md5(str(time.time_ns()).encode()).hexdigest()[:6]
    return f"note-{ts}-{rand}"


# ═══════════════════════════════════════════════════════════════
#  Index management
# ═══════════════════════════════════════════════════════════════

def _load_index() -> dict:
    """Load the notes index file."""
    if not NOTES_INDEX.exists():
        return {"notes": []}
    try:
        return json.loads(NOTES_INDEX.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"notes": []}


def _save_index(index: dict) -> None:
    """Save the notes index file."""
    _ensure_dirs()
    NOTES_INDEX.write_text(
        json.dumps(index, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _add_to_index(note_id: str, note_data: dict) -> None:
    """Add a note entry to the index."""
    index = _load_index()
    # Remove existing entry if present
    index["notes"] = [n for n in index["notes"] if n.get("id") != note_id]
    index["notes"].append(note_data)
    # Keep only the most recent MAX_NOTES entries
    if len(index["notes"]) > MAX_NOTES:
        index["notes"] = index["notes"][-MAX_NOTES:]
    _save_index(index)


def _remove_from_index(note_id: str) -> None:
    """Remove a note entry from the index."""
    index = _load_index()
    index["notes"] = [n for n in index["notes"] if n.get("id") != note_id]
    _save_index(index)


# ═══════════════════════════════════════════════════════════════
#  CRUD operations
# ═══════════════════════════════════════════════════════════════

def create_note(
    title: str,
    content: str,
    note_type: str = "insight",
    tags: list[str] | None = None,
    source_session: str | None = None,
    auto_generated: bool = False,
) -> str:
    """Create a new self-note.

    Args:
        title: The note title.
        content: The note body (markdown).
        note_type: One of lesson, pattern, decision, insight, tip, warning.
        tags: Optional list of tags.
        source_session: Optional session ID this note came from.
        auto_generated: Whether this note was auto-generated by the system.

    Returns:
        The note ID string.
    """
    _ensure_dirs()

    note_id = _generate_note_id()
    now = time.time()

    if note_type not in NOTE_TYPES:
        note_type = "insight"

    frontmatter = {
        "id": note_id,
        "created_at": now,
        "updated_at": now,
        "type": note_type,
        "tags": tags or [],
        "source_session": source_session,
        "auto_generated": auto_generated,
    }

    fm_lines = []
    for k, v in frontmatter.items():
        if isinstance(v, list):
            fm_lines.append(f"{k}: [{', '.join(v)}]")
        elif isinstance(v, bool):
            fm_lines.append(f"{k}: {str(v).lower()}")
        else:
            fm_lines.append(f"{k}: {v}")

    content = "---\n" + "\n".join(fm_lines) + "\n---\n\n" + content.strip() + "\n"

    path = _note_path(note_id)
    path.write_text(content, encoding="utf-8")

    _add_to_index(note_id, {
        "id": note_id,
        "title": title,
        "type": note_type,
        "tags": tags or [],
        "source_session": source_session,
        "auto_generated": auto_generated,
        "created_at": now,
        "updated_at": now,
    })

    return note_id


def list_notes(
    filter_type: str | None = None,
    tag: str | None = None,
    limit: int = 50,
) -> list[dict]:
    """List notes with optional filtering.

    Returns note summaries (not full content).
    """
    index = _load_index()
    notes = index.get("notes", [])

    if filter_type and filter_type in NOTE_TYPES:
        notes = [n for n in notes if n.get("type") == filter_type]

    if tag:
        notes = [n for n in notes if tag in n.get("tags", [])]

    # Sort by created_at descending (newest first)
    notes.sort(key=lambda n: n.get("created_at", 0), reverse=True)

    return notes[:limit]


def get_note(note_id: str) -> dict | None:
    """Get a full note by ID, including content and metadata."""
    path = _note_path(note_id)
    if not path.exists():
        return None
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return None

    # Parse frontmatter
    fm = {}
    body = content
    if content.startswith("---\n"):
        parts = content.split("---\n", 2)
        if len(parts) >= 3:
            fm_lines = parts[1].strip().splitlines()
            for line in fm_lines:
                if ":" in line:
                    k, v = line.split(":", 1)
                    k = k.strip()
                    v = v.strip()
                    if v.startswith("[") and v.endswith("]"):
                        v = [t.strip() for t in v[1:-1].split(",") if t.strip()]
                    fm[k] = v
            body = parts[2]

    index = _load_index()
    meta = next((n for n in index.get("notes", []) if n.get("id") == note_id), {})

    return {
        "id": note_id,
        "metadata": fm,
        "meta": meta,
        "content": body.strip(),
    }


def search_notes(query: str) -> list[dict]:
    """Search notes by title or content (simple substring match)."""
    index = _load_index()
    notes = index.get("notes", [])
    query_lower = query.lower()

    results = []
    for note in notes:
        title = note.get("title", "").lower()
        if query_lower in title:
            results.append(note)
            continue
        # Also check content
        note_data = get_note(note.get("id", ""))
        if note_data and query_lower in note_data.get("content", "").lower():
            results.append(note)

    return results


def delete_note(note_id: str) -> bool:
    """Delete a note by ID. Returns True on success."""
    path = _note_path(note_id)
    if path.exists():
        try:
            path.unlink()
        except OSError:
            return False
    _remove_from_index(note_id)
    return True


def get_note_count() -> int:
    """Return the total number of notes."""
    index = _load_index()
    return len(index.get("notes", []))


# ═══════════════════════════════════════════════════════════════
#  Auto-generation
# ═══════════════════════════════════════════════════════════════

def auto_generate_note(
    interactions: list[dict] | None = None,
    patterns: list[dict] | None = None,
    tips: list[dict] | None = None,
) -> list[str]:
    """Analyze session data and auto-create notes.

    Returns a list of created note IDs.
    """
    created: list[str] = []

    if patterns:
        # Generate a note for significant patterns
        top_patterns = sorted(patterns, key=lambda p: -p.get("count", 0))[:3]
        for p in top_patterns:
            ptype = p.get("type", "unknown")
            count = p.get("count", 0)
            if count < 3:
                continue

            if ptype == "frequent_tool":
                tool = p.get("tool", "unknown")
                title = f"Frequent tool: {tool}"
                content = (
                    f"The `{tool}` tool has been used {count} times in this session. "
                    f"Consider whether this pattern indicates a recurring workflow "
                    f"that could be automated or turned into a reusable skill."
                )
                note_id = create_note(
                    title=title,
                    content=content,
                    note_type="pattern",
                    tags=["auto", "tool", tool],
                    auto_generated=True,
                )
                created.append(note_id)

            elif ptype == "topic":
                kw = p.get("keyword", "topic")
                title = f"Frequent topic: {kw}"
                content = (
                    f"The topic \"{kw}\" appeared {count} times in this session. "
                    f"The user seems to have a recurring interest in this area. "
                    f"Consider keeping relevant context ready for future sessions."
                )
                note_id = create_note(
                    title=title,
                    content=content,
                    note_type="pattern",
                    tags=["auto", "topic", kw],
                    auto_generated=True,
                )
                created.append(note_id)

            elif ptype == "repetition":
                kws = ", ".join(p.get("keywords", [])[:3])
                title = f"Repeated pattern: {kws}"
                content = (
                    f"A repeated request pattern was detected {count} times: {kws}. "
                    f"This suggests the user has a recurring task that could benefit "
                    f"from a reusable skill or saved workflow."
                )
                note_id = create_note(
                    title=title,
                    content=content,
                    note_type="pattern",
                    tags=["auto", "repetition"],
                    auto_generated=True,
                )
                created.append(note_id)

    if tips:
        active_tips = [t for t in tips if not t.get("applied", False)]
        if active_tips:
            title = "Self-improvement tips available"
            content = (
                f"The self-improvement system has {len(active_tips)} active tip(s):\n\n"
            )
            for t in active_tips[:5]:
                content += f"- {t.get('message', '')}\n"
            content += "\nReview these tips to improve agent behaviour."
            note_id = create_note(
                title=title,
                content=content,
                note_type="tip",
                tags=["auto", "tips"],
                auto_generated=True,
            )
            created.append(note_id)

    return created


# ═══════════════════════════════════════════════════════════════
#  Context injection
# ═══════════════════════════════════════════════════════════════

def get_notes_for_context() -> str:
    """Return all notes as a formatted string for injection into the system prompt.

    Only returns non-auto-generated notes (the agent's own reflections).
    """
    notes = list_notes(limit=100)
    if not notes:
        return ""

    lines = [f"  {BOLD}Agent Self-Notes{RESET}"]
    lines.append(f"  {DIM}{'─' * 46}{RESET}")

    for n in notes:
        if n.get("auto_generated"):
            continue
        title = n.get("title", "?")
        ntype = n.get("type", "insight")
        tags = n.get("tags", [])
        tag_str = f" [{', '.join(tags)}]" if tags else ""
        lines.append(f"  {DIM}[{ntype}]{RESET} {title}{tag_str}")

    return "\n".join(lines)


# Patch for ANSI codes (used by get_notes_for_context)
try:
    from agent import BOLD, DIM, RESET
except ImportError:
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"